changelog:
  categories:
    - title: Breaking Changes
      labels:
        - release:major
    - title: Features
      labels:
        - release:minor
    - title: Fixes
      labels:
        - release:patch
    - title: Other Changes
      labels:
        - "*"
