from collections.abc import Callable
from dataclasses import dataclass

BuildEventListText = Callable[[set[str], str | None], str]


@dataclass(frozen=True, slots=True)
class BotTexts:
    WELCOME_TEXT: str
    START_BUTTON_FOLLOW: str
    START_BUTTON_UNFOLLOW: str
    START_BUTTON_EVENTS: str
    BUTTON_BACK: str
    START_BUTTON_ADMIN: str
    ADMIN_BUTTON_SUBSCRIPTIONS: str
    ADMIN_MENU_TEXT: str
    ADMIN_BUTTON_BROADCAST: str
    ADMIN_BROADCAST_MENU_TEXT: str
    ADMIN_BROADCAST_ALL: str
    ADMIN_BROADCAST_BY_NO: str
    ADMIN_BROADCAST_ENTER_MESSAGE_ALL: str
    ADMIN_BROADCAST_ENTER_NO_IDS: str
    ADMIN_BROADCAST_NO_IDS_INVALID: str
    ADMIN_BROADCAST_CONFIRM_HINT: str
    ADMIN_BROADCAST_PREVIEW_ALL: str
    ADMIN_BROADCAST_PREVIEW_SELECTED: str
    BUTTON_SEND_BROADCAST: str
    ADMIN_PRIVATE_CHAT_REQUIRED: str
    NO_NEW_BLOCKS_ADMIN_ALERT: str
    FOLLOW_NODE_OPERATOR_TEXT: str
    FOLLOW_NODE_OPERATOR_FOLLOWING: str
    UNFOLLOW_NODE_OPERATOR_TEXT: str
    UNFOLLOW_NODE_OPERATOR_NOT_FOLLOWING: str
    UNFOLLOW_NODE_OPERATOR_FOLLOWING: str
    NODE_OPERATOR_FOLLOWED: str
    NODE_OPERATOR_CANT_FOLLOW: str
    NODE_OPERATOR_UNFOLLOWED: str
    NODE_OPERATOR_CANT_UNFOLLOW: str
    build_event_list_text: BuildEventListText
